config/routes.rb
Rails.application.routes.draw do

  root to: 'products#index'
  resources :products
  resources :users, except: [:destroy]

  #facebook login
  match 'auth/:provider/callback', to: 'sessions#create', via: 'get'
  match 'auth/failure', to: redirect('/'), via: 'get'
  match 'signout', to: 'sessions#destroy', as: 'signout', via: 'get'

  #venmo access
  get 'venmo', to: 'users#venmo'
  get 'venmo_auth', to: 'users#venmo_auth'

  #transaction flow
  post 'purchase/:id', to: 'users_products#buyer_purchase_intent', as: 'purchase'
  post 'accept/:id', to: 'users_products#seller_accept_offer', as: 'accept'
  post 'decline/:id', to: 'users_products#seller_decline_offer', as: 'decline'

	#venmo webhook auth (temp)
	get 'webhook_url', to: 'users#webhook_verify'

end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :users_products
	has_many :products, through: :users_products

  #adding omniauth code for user sign-in from RailsCast
  def self.from_omniauth(auth)

    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.location = auth.info.location
      user.image = auth.info.image
      user.full_name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
    #BeeThreeMailer.signup_confirmation(@user).deliver
  end

  def add_venmo(code)
    response = Typhoeus.post("https://api.venmo.com/v1/oauth/access_token", params: { client_id: ENV['VENMO_CLIENT_ID'], code: code, client_secret: ENV['VENMO_CLIENT_SECRET']})
    response_parsed = JSON.parse(response.body)
    # TODO: handle error response

    token = response_parsed['access_token']
    expiry = DateTime.now + 60.days
    token_type = response_parsed['token_type']
    refresh = response_parsed['refresh_token']
    venmo_id = response_parsed['user']['id']
    venmo_email = response_parsed['user']['email']

    self.update(venmo_access_token: token, venmo_expires_at: expiry, venmo_token_type: token_type, venmo_refresh_token: refresh, venmo_id: venmo_id,  venmo_email: venmo_email)
    #TODO: check that tokens were not nil and were saved, return response to controller

  end

  def facebook
    @facebook ||= Koala::Facebook::API.new(oauth_token)
  end

  def get_friends
    friends = self.facebook.get_connection("#{self.uid}", "friends")
    return friends
  end

  def friends_sales
    friends = self.get_friends
    for_sale = []
    seller = Role.find_by(name: 'Seller')
    open = TxnStatus.find_by(name: 'Listed')

    friends.each do |friend|
      fb_id = friend['id']
      local_friend = User.find_by(uid: fb_id)

      unless local_friend.nil?
        friend_txns = UsersProducts.where(user_id: local_friend.id).where(role_id: seller.id).where(txn_status_id: open.id)
        friend_txns.each do |sale|
          for_sale.push(sale.product)
        end
      end

    end
    return for_sale
  end

  def my_sales
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_filter :signed_in_user, only: [:new]
  skip_before_filter :venmo_check, only: [:new, :venmo, :venmo_auth]
  
	def index
		redirect_to user_path(@current_user.id)
	end

	def show
		@all_transactions = UsersProducts.where(user_id: current_user.id)
	end

	def new
  	# after successful signup/login, redirect_to venmo_path
  end

	def create
	end

	def update
	end

  def venmo
  end

  def venmo_auth
  	if (params['error'] != nil) || (params['state'] != 'b3b3b3')
  		redirect_to venmo_path, notice: 'We were not able to connect to your Venmo account which is required for the use of beeThree. We require this so we can facilitate your purchases with friends. Please try again.'
  	else
	  	code = params['code']
	  	@current_user.add_venmo(code)
	  	#TODO: check response from user method that token was successfully saved
	  	redirect_to products_path, notice: "You're all set to shop!"
	  end
  end

  #venmo webhook auth (temp)
  def webhook_verify
  	render :text => params[:venmo_challenge].to_s
  end

end

app/views/users/new.html.erb
<div class="header-image img-rounded">
  <div class="headline">
    <h1>beeThree</h1>
    <h2>a marketplace among friends</h2>
    <br><br>
    <h3><%= link_to "Sign in with Facebook", "/auth/facebook", class: "fb", id: "sign_in" %></h3>
  </div>  
</div>

app/views/users/show.html.erb
<% @all_transactions.each do |txn| %>

<% if txn.seller? %>
<div class="panel panel-info user-txn">
<% else %>
<div class="panel panel-warning user-txn">
<%end %>

  <div class="panel-heading">
  	<h4><span><%= txn.product.name %></span>
  	<span class="pull-right">$<%= txn.product.price %></span></h4>
  </div>

  <div class="panel-body">
  	<span class="col-xs-3">
  		<%= image_tag txn.product.avatar.url(:medium), class: "img-rounded img-responsive pull-left txn-product-image" %>
		</span>

		<div class="col-xs-6 txn-product-info">
	  	<p><%= txn.product.description %></p>

	  	<!-- edit-delete-buttons shown only when role=seller -->
	  	<% if txn.seller? %>
	  	<div class="align-buttons-to-bottom edit-delete-buttons">
	  		<%= button_to "Edit", product_path(txn.product), method: :get, class: "btn btn-warning" %>
			</div>
			<% end %>
		</div>

		<div class="col-xs-3 txn-status-options">
			<div class="well well-sm seller-friend">
				<span class="pull-left">
					<strong><%= txn.visible_status %></strong><br>
					<% unless txn.transact_with == nil %>
					<%= txn.status_preposition+' '+txn.transact_with.user.first_name+' '+txn.transact_with.user.last_name %><br>
					<% end %>
					as of <%= txn.updated_at.to_date.to_formatted_s(:long) %>
				</span>
				<% unless txn.transact_with == nil %>
				<span class="pull-right"><%= image_tag txn.transact_with.user.image, class: 'img-rounded img-responsive friend-image' %></span>
				<% end %>
			</div>

			<!-- pending-seller-buttons shown only when role=seller and txn_status=pending -->
			<% if txn.seller? && txn.txn_status.pending? %>
			<div class="align-buttons-to-bottom pending-seller-buttons">
				<span class="pull-left"><%= button_to "Approve Sale", accept_path(txn), data: {confirm: "Please confirm. You are selling your #{txn.product.name.downcase} to #{txn.transact_with.user.first_name}."}, method: :post, class: "btn btn-success" %></span>
				<span class="pull-right"><%= button_to "Decline Sale", decline_path(txn), data: {confirm: "Are you sure you don't want to sell your #{txn.product.name.downcase} to #{txn.transact_with.user.first_name}?"}, method: :post, class: "btn btn-danger" %></span>
			</div>
			<% end %>
		</div>

	</div>
</div>
<% end %>

app/views/users/venmo.html.erb
<img src="https://s3.amazonaws.com/venmo/venmo_logo_blue.png" height="100" width="300">

<div class="venmo">
	<h2><a href="https://api.venmo.com/v1/oauth/authorize?client_id=1741&scope=make_payments%20access_email&response_type=code&state=b3b3b3">Activate with Venmo</a></h2>
</div>


<h2>About</h2>
Make and share payments. 
Connect with people, send money for free, and cash out to any bank overnight.

<h2>Mission</h2>
To make the experience of paying your friends as simple and fun as possible.

<h2>Company Overview</h2>
Venmo is the best way to pay your friends. It’s simple and free to use. Download it for the iPhone and Android today!

<h2>Description</h2>
Venmo works on your iPhone, Android, Blackberry, via text on any mobile device, or on your desktop. We make it simple for people to pay for the fun things they do together.