config/routes.rb
Rails.application.routes.draw do

  root to: 'products#index'
  resources :products
  resources :users, except: [:destroy]

  #facebook login
  match 'auth/:provider/callback', to: 'sessions#create', via: 'get'
  match 'auth/failure', to: redirect('/'), via: 'get'
  match 'signout', to: 'sessions#destroy', as: 'signout', via: 'get'

  #venmo access
  get 'venmo', to: 'users#venmo'
  get 'venmo_auth', to: 'users#venmo_auth'

  #transaction flow
  post 'purchase/:id', to: 'users_products#buyer_purchase_intent', as: 'purchase'
  post 'accept/:id', to: 'users_products#seller_accept_offer', as: 'accept'
  post 'decline/:id', to: 'users_products#seller_decline_offer', as: 'decline'

	#venmo webhook auth (temp)
	get 'webhook_url', to: 'users#webhook_verify'

end

app/models/product.rb
 class Product < ActiveRecord::Base

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  has_many :users, through: :users_products
  has_one :venmo_charge
  belongs_to :status
  # has_many :users

  validates :name, presence: true, length: {minimum: 2, maximum: 50}
  validates :description, presence: true, length: {minimum: 2, maximum: 1000}
  validates :price, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than: 3000 }
  validates :avatar, presence: true

  def seller
  	seller_role = Role.find_by(name: 'Seller')
  	seller_txn = UsersProducts.where(product_id: self.id).where(role_id: seller_role.id).first
  	seller = seller_txn.user
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include ProductsHelper
  # before_filter :product_check, only: [:show]

	def index
    @friends_sales = @current_user.friends_sales
	end

	def new
		@product = Product.new
	end
	
	def create
    @product = Product.new(product_params)
    if @product.save
      # adds a transaction record in UsersProducts to associate user as the seller of this product
      open = TxnStatus.find_by(name: 'Listed')
      seller = Role.find_by(name: 'Seller')
      UsersProducts.create(user_id: @current_user.id, product_id: @product.id, role_id: seller.id, txn_status_id: open.id)
      redirect_to @product, notice: 'Item was successfully created.'
    else
      redirect_to new_product_path, notice: 'Item was NOT created. Please try again.'
    end
  end

  def edit
  	@product = Product.find(params[:id])
  end

  def update
  	@product = Product.find(params[:id])
  	@product.update(product_params)

  	if @product.save
  	redirect_to @product
    else
    redirect_to @product, notice: 'Item was NOT updated. Please try again.'
  	end
  end

  def show
		@product = Product.find(params[:id])
	end

  def destroy
    Product.find(params[:id]).destroy
    redirect_to products_path
  end

  private
	  def product_params
	    params.require(:product).permit(:avatar, :name, :description, :price)
	  end
end

app/helpers/products_helper.rb
module ProductsHelper
#check to show prodcuts that you own and your friends own on show page

  def product_check
    accessible_products = current_user.friends_sales

    current_users_txns = UsersProducts.where(user_id: current_user.id)

    current_users_txns.each do |txn|
      accessible_products.push(txn.product)
    end

    # @product = Product.find(params[:id])
    unless accessible_products.include?(@product)
      redirect_to products_path, notice: "That product is not available."
    end
  end

end

app/views/products/index.html.erb
<% @friends_sales.each do |product| %>

<div class="panel panel-warning user-txn">
	
	<div class="panel-heading">
		<h4><span><%= product.name %></span>
		<span class="pull-right">$<%= product.price %></span></h4>
	</div>

	<div class="panel-body">
		<span class="col-xs-3">
			<%= image_tag product.avatar.url(:medium), class: "img-rounded img-responsive pull-left txn-product-image" %>
		</span>
	
		<div class="col-xs-6 txn-product-info">
	  	<p><%= product.description %></p>
	  </div>

	  <div class="col-xs-3 txn-status-options">
			<div class="well well-sm seller-friend">
				<span class="pull-left friend-name"><%= product.seller.full_name %></span>
				<span class="pull-right"><%= image_tag product.seller.image, class: 'img-rounded img-responsive friend-image' %></span>
			</div>

	  	<div class="align-buttons-to-bottom">
				<span class="pull-left"><%= button_to "View Listing", product_path(product), method: :get, class: "btn btn-warning" %></span>
				<span class="pull-right"><%= button_to "Buy This Item", purchase_path(product), data: {confirm: "Please confirm you want to buy #{product.seller.first_name}'s #{product.name.downcase}. Once the seller accepts, you will be charged via Venmo."}, method: :post, class: "btn btn-warning" %></span>
			</div>
		</div>

	</div>
</div>	

<% end %>

app/views/products/new.html.erb
<div class="panel panel-default user-txn">
  
  <div class="panel-heading">
    <span><h4>New Product</h4></span>
  </div>

  <div class="panel-body">
    <div class="col-xs-9">
      <div role="form" class="col-xs-12">
        <%= form_for(@product) do |f| %>

        <div class="form-group">
            <%= f.label :name %><br>
            <%= f.text_field :name %>
        </div>

        <div class="form-group">
          <%= f.label :description %><br>
          <%= f.text_field :description %>
        </div>

        <div class="form-group">
          <%= f.label :price %><br>
          <%= f.number_field :price %>
        </div>

        <div class="form-group">
          <%= f.file_field :avatar %><br>
        </div>

        <%= f.submit %>

        <% end %>
      </div>
    </div>

    <div class="col-xs-3 product-options">
      <div class="well well-sm seller-friend">
        <span class="pull-left friend-name"><%= @current_user.full_name %></span>
        <span class="pull-right"><%= image_tag @current_user.image, class: 'img-rounded img-responsive friend-image' %></span>
      </div> 
    </div>

  </div>
</div>

app/views/products/show.html.erb
<div class="panel panel-default user-txn">
  
  <div class="panel-heading">
    <h4><span><%= @product.name %></span>
    <span class="pull-right">$<%= @product.price %></span></h4>
  </div>

  <div class="panel-body">
    <span class="col-xs-12 col-sm-5">
      <%= image_tag @product.avatar.url(:medium), class: "img-rounded img-responsive pull-left product-show-image" %>
    </span>
  
    <div class="col-xs-6 col-sm-4 product-info">
      <p><%= @product.description %></p>
    </div>

    <div class="col-xs-6 col-sm-3 product-options">
      <div class="well well-sm seller-friend">
        <span class="pull-left friend-name"><%= @product.seller.full_name %></span>
        <span class="pull-right"><%= image_tag @product.seller.image, class: 'img-rounded img-responsive friend-image' %></span>
      </div>

      <div class="buy-edit-button">
      <% if current_user == @product.seller %>
        <button type="button" class="btn btn-warning" id="edit">Edit This Listing</button>
      <% else %>
        <%= button_to "Buy #{@product.seller.first_name}'s #{@product.name}", purchase_path(@product), data: {confirm: "Please confirm you want to buy #{@product.seller.first_name}'s #{@product.name.downcase}. Once the seller accepts, you will be charged via Venmo."}, method: :post, class: "btn btn-warning" %>
      <% end %>
      </div>
      
      <div role="form" id="edit-form">
        <%= form_for @product do |f| %>

        <div class="form-group">
            <%= f.label :name %><br>
            <%= f.text_field :name %>
        </div>

        <div class="form-group">
          <%= f.label :description %><br>
          <%= f.text_field :description %>
        </div>

        <div class="form-group">
          <%= f.label :price %><br>
          <%= f.number_field :price %>
        </div>

        <div class="form-group">
          <%= f.file_field :avatar %><br>
        </div>

        <%= f.submit %>

        <% end %>
      </div>
    </div>

  </div>
</div>